### ISSUE TITLE
Add support for other fluids

### ISSUE THREAD

**Issue by mbhewitt** [Bluetooth-Devices/mopeka-iot-ble#13]
**Is your feature request related to a problem? Please describe.**
The Universal mopeka sensor supports multiple fluid types. The current output is in mm of propane which is an inaccurate reading for other fluid types. It loses precision when converting to an int.

**Describe the solution you'd like**
A drop down for each sensor to describe the fluid it is sensing. You can find the coefficients for other fluids here: https://gist.github.com/dirkjanfaber/2a3238f041310d44af030bf1bdb5e5ad

Provide the tank_level reading as a float instead of an int.

Provide the raw sensor reading. tank_level_raw

Remove the quality requirement for publication or lower it.

**Comment by bb12489** [comment]
I've just come across this issue as well. I hope support for it comes soon! I read over on the Victron forum that Mopeka has discontinued their old water and propane sensors and will be moving forward with just the universal sensors.

**Comment by cayossarian** [comment]
As an adjunct to the OP's request the top down sensors like TD40/200 would use 'air' coefficients which are also found in the link the OP provided.
