### ISSUE TITLE
Mopeka Universal Sensor isn´t recognized through HA

### ISSUE THREAD

**Issue by ak68-hub** [Bluetooth-Devices/mopeka-iot-ble#16]
I use 2 new Mopeka Universal Sensors 
(HA on Raspery 5 with BT/ Ruuvi Tag´s work fine !)

They work fine with Venus OS, but not with HA.
HA doesn´t find them during search- 50cm away :)

What can I do ?
Thank you !

**Comment by bdraco** [comment]
https://github.com/Bluetooth-Devices/mopeka-iot-ble/issues/9
